"""Native proof-bearing rule identity and composition."""

from ._identity import cluster_rule_objects, rule_objects_isomorphic
from .composition import (
    CompositionCertificate,
    CompositionError,
    CompositionIssue,
    CompositionIssueCode,
    CompositionProvenance,
    CompositionReplay,
    CompositionResult,
    ProvenanceRef,
    RuleOverlap,
    compose_rules,
)
from .search import (
    CompositionClass,
    CompositionSearchResult,
    CompositionWitness,
    OverlapSearchError,
    OverlapSearchIssue,
    OverlapSearchIssueCode,
    OverlapSearchLimits,
    RejectedOverlap,
    canonical_overlap_digest,
    canonical_rule_identity,
    enumerate_overlaps,
    rule_spans_isomorphic,
    search_compositions,
)

__all__ = [
    "CompositionCertificate",
    "CompositionClass",
    "CompositionError",
    "CompositionIssue",
    "CompositionIssueCode",
    "CompositionProvenance",
    "CompositionReplay",
    "CompositionResult",
    "CompositionSearchResult",
    "CompositionWitness",
    "OverlapSearchError",
    "OverlapSearchIssue",
    "OverlapSearchIssueCode",
    "OverlapSearchLimits",
    "ProvenanceRef",
    "RuleOverlap",
    "RejectedOverlap",
    "canonical_overlap_digest",
    "canonical_rule_identity",
    "cluster_rule_objects",
    "compose_rules",
    "enumerate_overlaps",
    "rule_objects_isomorphic",
    "rule_spans_isomorphic",
    "search_compositions",
]
