package:
  name: synkit
  version: 0.0.11b1

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - scikit-learn >=1.4.0
    - pandas >=1.5.3
    - rdkit >=2025.3.1
    - networkx >=3.3
    - seaborn >=0.13.2
    - requests >=2.32.3
    - regex >=2024.11.6

about:
  home:       https://github.com/TieuLongPhan/SynKit
  license:    MIT
  license_file: LICENSE
  summary:    Utility for reaction modeling using graph grammar

extra:
  recipe-maintainers:
    - TieuLongPhan
