package:
  name: synkit
  version: "1.1.0"

source:
  path: ..

build:
  noarch: python
  number: 0
  script:
    # pip will invoke Hatchling to build and install the wheel, including data files
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.11,<3.12     # ensure same Python minor version
    - pip
    - hatchling               # PEP517 build backend
  run:
    - python >=3.11,<3.12
    - scikit-learn >=1.4.0
    - pandas >=1.5.3
    - rdkit >=2025.3.1
    - networkx >=3.3
    - seaborn >=0.13.2
    - requests >=2.32.3
    - regex >=2024.11.6
    - numpy >=2.2.0

about:
  home:        https://github.com/TieuLongPhan/SynKit
  license:     MIT
  license_file: LICENSE
  summary:     Utility for reaction modeling using graph grammar

extra:
  recipe-maintainers:
    - TieuLongPhan
