{% set project      = load_pyproject_data(path="../pyproject.toml") %}
{% set base_version = project['project']['version'] %}

{#– get run-number from the environment, default “0” –#}
{% set run = environ.get('GITHUB_RUN_NUMBER', '0') %}

{#– compose prerelease version –#}
{% set version = base_version ~ 'b' ~ run %}

package:
  name: {{ project['project']['name']|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ run | int }}      # ← guaranteed integer
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.11
    - pip
  run:
{% for dep in project['project']['dependencies'] %}
    - {{ dep }}
{% endfor %}

about:
  home:       https://github.com/TieuLongPhan/SynKit
  license:    MIT
  license_file: LICENSE
  summary:    Utility for reaction modeling using graph grammar

extra:
  recipe-maintainers:
    - TieuLongPhan
