# Tell RTD to use v2 of the config schema (not your project version)
version: 2

build:
  os: ubuntu-22.04

python:
  version: 3.11
  install:
    # Install your package along with the "docs" extras
    - method: pip
      path: .
      extra_requirements: docs

sphinx:
  configuration: doc/conf.py
  builder: html
