# .readthedocs.yml
# Read the Docs configuration for SynKit documentation

version: 2

build:
  os: ubuntu-22.04

python:
  version: 3.11
  install:
    # install your package so autodoc can import it
    - method: pip
      path: .
    - extra_requirements: docs

sphinx:
  configuration: doc/conf.py
  builder: html
