"""Vector drawing layer; scientific results are supplied by the audited runners.

Chemical conventions follow thesis Chapters 03 and 10. Endpoint bonds and ITS
states come directly from frozen adjacency matrices, never from drawn geometry.
"""

from itertools import combinations
from math import cos, sin, pi, hypot, log10
from pathlib import Path

FIGURES = Path(__file__).resolve().parents[1] / "paper/synister/figures"


class Canvas:
    def __init__(self, height):
        self.lines = [
            r"% Generated by scripts/synister_diagrams.py.",
            r"\begin{tikzpicture}[x=1cm,y=1cm]",
            r"\syndesign{16}",
            rf"\path[use as bounding box] (0,.05) rectangle (16,-{height});",
        ]

    def add(self, line):
        self.lines.append(line)

    def text(self, x, y, text, style="synlabel"):
        self.add(rf"\node[{style}] at ({x:.3f},{y:.3f}) {{{text}}};")

    def head(self, x, y, letter, title):
        self.add(rf"\synpanelhead{{{x},{y}}}{{{letter}}}{{{title}}}")

    def line(self, p, q, style="synbond"):
        self.add(rf"\draw[{style}] ({p[0]:.3f},{p[1]:.3f}) -- ({q[0]:.3f},{q[1]:.3f});")

    def dot(self, x, y, color="npgBlue", radius=0.065):
        self.add(rf"\fill[{color}] ({x:.3f},{y:.3f}) circle ({radius});")

    def save(self, name):
        (FIGURES / name).write_text(
            "\n".join(self.lines + [r"\end{tikzpicture}"]) + "\n"
        )


def graph(c, coords, states, atoms=None, ids=None, paired=False, node_numbers=False, active_atoms=None):
    """Skeletal molecules or paired graphs; each node/edge remains data-backed."""
    for i, (name, _, _) in (ids or {}).items():
        x, y = coords[i]
        color = "npgBlue" if name == "a" else "npgPurple"
        c.add(
            rf"\filldraw[fill={color}!9,draw={color}!60,line width=.55pt] ({x},{y}) circle (.245);"
        )
    for i, j, before, after in states:
        p, q = coords[i], coords[j]
        style = "synbond"
        if active_atoms is not None and not {i, j} <= set(active_atoms):
            style += ',opacity=.23'
        if paired:
            style = (
                "synbond,draw=figMuted!75"
                if before == after
                else ("synbroken" if after == 0 else "synformed")
            )
        order = max(before, after)
        assert order in (1, 2) and (before == after or min(before, after) == 0)
        if order == 1:
            c.line(p, q, style)
        else:
            length = hypot(q[0] - p[0], q[1] - p[1])
            dx, dy = -(q[1] - p[1]) / length * 0.035, (q[0] - p[0]) / length * 0.035
            for sign in (-1, 1):
                c.line(
                    (p[0] + sign * dx, p[1] + sign * dy),
                    (q[0] + sign * dx, q[1] + sign * dy),
                    style,
                )
    hcl = (
        []
        if paired or atoms is None
        else [
            i
            for i, atom in enumerate(atoms)
            if atom["element"] == "Cl" and atom["hydrogens"] == 1
        ]
    )
    if len(hcl) == 2:
        assert not any(i in hcl or j in hcl for i, j, _, _ in states)
    for i, (x, y) in enumerate(coords):
        if atoms is None:
            c.dot(x, y, "figNavy", 0.045)
            if node_numbers:
                c.text(x, y - 0.19, str(i + 1), "synsmall")
            continue
        atom = atoms[i]
        element = atom["element"]
        if element == "C":
            continue  # skeletal carbon: vertex or bond end, as in Chapter 10
        h = atom["hydrogens"] if not paired else 0
        text = (
            element
            + ("H" if h else "")
            + (rf"\ensuremath{{_{{{h}}}}}" if h > 1 else "")
        )
        if element == "Cl" and h == 1:
            text = "HCl"
            if len(hcl) == 2 and active_atoms is None:
                if i == hcl[1]:
                    continue
                x = sum(coords[j][0] for j in hcl) / 2
                y = sum(coords[j][1] for j in hcl) / 2
                text = r"\textcolor{figInk}{2\,H}Cl"
        opacity = ',opacity=.23' if active_atoms is not None and i not in active_atoms else ''
        c.text(x, y, text, f"synchem,text=chem{element}"+opacity)
    for i, (name, dx, dy) in (ids or {}).items():
        x, y = coords[i]
        color = "npgBlue" if name == "a" else "npgPurple"
        c.text(x + dx, y + dy, name, f"synidx,text={color}")


def edges(matrix):
    return [
        (i, j, matrix[i][j], matrix[i][j])
        for i, j in combinations(range(len(matrix)), 2)
        if matrix[i][j]
    ]


def shift(coords, x, y, scale=1):
    return [(x + a * scale, y + b * scale) for a, b in coords]


# The acid backbone is aligned identically in both endpoint drawings.
RCOORDS = [
    (0.2, 0),
    (0.82, 0.36),
    (2.15, 0),
    (2.77, 0.36),
    (3.39, 0),
    (3.39, -0.72),
    (4.01, 0.36),
    (4.01, 1.08),
    (4.63, 0),
    (6.1, 1.08),
    (6.1, 0.36),
    (5.48, 0),
    (6.72, 0),
]
PCOORDS = [
    (4.32, 0),
    (3.70, 0.36),
    (3.08, 0),
    (3.08, -0.72),
    (2.46, 0.36),
    (2.46, 1.08),
    (1.84, 0),
    (1.22, 0.36),
    (5.50, 0.30),
    (5.50, -0.40),
    (6.65, 0),
    (7.27, 0.36),
    (7.89, 0),
]


def draw_input(record):
    c = Canvas(6.4)
    c.head(0.1, -0.08, "A", "Unmapped endpoints")
    graph(
        c,
        shift(RCOORDS, 0.05, -1.75),
        edges(record["endpoint_adjacency"][0]),
        record["endpoint_inventories"][0],
    )
    graph(
        c,
        shift(PCOORDS, 8.20, -1.75, 0.90),
        edges(record["endpoint_adjacency"][1]),
        record["endpoint_inventories"][1],
    )
    for x in (1.52, 5.15):
        c.text(x, -1.55, "$+$")
    for x in (12.52, 13.75):
        c.text(x, -1.55, "$+$")
    c.line((7.15, -1.5), (8.65, -1.5), "synflow")
    c.line((0.1, -2.95), (15.9, -2.95), "draw=figHair,line width=.5pt")
    c.head(0.1, -3.12, "B", "Find the minimum")
    c.head(8.05, -3.12, "C", "Group the eight minima")
    # Full literal histogram, including the actual small minimum bar on a log axis.
    hist = {int(k): v for k, v in record["oracle"]["cd_histogram"].items()}
    c.line((0.8, -5.85), (7.2, -5.85), "draw=figMuted,line width=.5pt")
    c.line((0.70, -5.85), (0.70, -4.1), "draw=figMuted,line width=.5pt")
    for count in (10, 100, 1000):
        y = -5.85 + 0.53 * log10(count)
        c.line((0.65, y), (0.70, y), "draw=figMuted,line width=.5pt")
        c.text(0.55, y, str(count), "synsmall,anchor=east")
    for cost, count in sorted(hist.items()):
        x = 0.96 + (cost - 6) * 0.325
        height = log10(count) * 0.53
        color = "npgGreen" if cost == 6 else "npgBlue!35"
        c.add(
            rf"\fill[{color}] ({x-.16:.3f},-5.85) rectangle ({x+.16:.3f},{-5.85+height:.3f});"
        )
        c.text(x, -6.12, str(cost), "synsmall")
    c.text(4.0, -3.93, r"$|\Omega|=5{,}760$", "synlabel")
    c.text(1.45, -4.63, r"$C^*=6$", "synlabel,text=npgGreen!80!black")
    c.line((1.35, -4.95), (0.96, -5.34), "synflow,draw=npgGreen")
    c.text(7.48, -6.12, "CD", "synsmall")
    # Eight actual maps, grouped into the two product orbits / ITS classes.
    for k, color in enumerate(("npgBlue", "npgPurple")):
        yy = -4.22 - k * 1.2
        c.add(
            rf"\draw[draw={color},fill={color}!5,rounded corners=5pt] (8.85,{yy-.29}) rectangle (11.0,{yy+.29});"
        )
        for j in range(4):
            c.dot(9.15 + j * 0.50, yy, color, 0.10)
        c.line((11.3, yy), (12.60, yy), "synflow")
        cls = record["classes"][k]
        # Distinct local bond-change signatures, taken from the actual ITS record.
        indices = [1, 6, 8, 10, 11, 12] if k == 0 else [8, 0, 1, 10, 11, 12]
        points = shift(
            [(0, 0), (0.3, 0.18), (0.6, 0), (0.9, 0.18), (1.2, 0), (0.9, 0.55)],
            13.05,
            yy - 0.15,
        )
        lookup = {v: i for i, v in enumerate(indices)}
        states = [(lookup[i], lookup[j], a, b) for i, j, a, b in cls["bond_edits"]]
        graph(c, points, states, paired=True)
        c.text(15.05, yy, chr(65 + k), "synlabel,text=" + color)
    for x, text in ((9.93, "2 orbits"), (13.85, "2 ITS")):
        c.text(x, -6.13, text, "synsmall")
    c.save("worked_unmapped.tex")


def draw_classes(record):
    c = Canvas(9.4)
    # Small shared reactant key: identity tags are separate from element colors.
    c.head(0.1, -0.08, "A", "Two oxygen origins")
    c.text(14.60, -0.35, r"$\CD=6$", "synsmall")
    # Only the two oxygen-source molecules are needed here; the complete
    # balanced endpoints appear once in the preceding chemical figure.
    graph(
        c,
        shift(RCOORDS[:9], 5.5, -1.8, 0.98),
        [edge for edge in edges(record["endpoint_adjacency"][0]) if max(edge[:2]) < 9],
        record["endpoint_inventories"][0][:9],
        {1: ("a", 0.23, 0.20), 8: ("b", 0.23, -0.12)},
    )
    c.text(7.02, -1.58, "$+$")
    c.line((7.8, -2.75), (4, -3.00), "synflow")
    c.line((8.2, -2.75), (12, -3.00), "synflow")
    a, b = record["endpoint_adjacency"]
    for k, cls in enumerate(record["classes"]):
        ox = k * 8.05
        c.head(ox + 0.10, -2.92, chr(66 + k), f"Class {chr(65+k)}")
        m = cls["representative"]
        # Skeletal product structure; the two tags reveal oxygen provenance.
        product_points = shift(PCOORDS, ox - 0.35, -4.45, 0.92)
        tags = {m[1]: ("a", 0.20, 0.20), m[8]: ("b", 0.20, 0.20)}
        graph(c, product_points, edges(b), record["endpoint_inventories"][1], tags)
        for x in (4.00, 5.27):
            c.text(ox + x, -4.25, "$+$")
        c.text(ox + 0.22, -5.50, "ITS", "synsmall,anchor=west")
        # Full thirteen-atom ITS; layouts avoid crossings, identities stay fixed.
        points = [
            (0.65, -6.05),
            (1.75, -5.5),
            (0.65, -7.2),
            (1.75, -7.8),
            (2.85, -7.2),
            (3.95, -7.8),
            (2.85, -6.05),
            (2.85, -5.1),
            (3.95, -5.5),
            (6.15, -5.5),
            (5.05, -6.05),
            (5.05, -7.2),
            (6.15, -6.65),
        ]
        if k:
            points = [
                (2.85, -6.05),
                (3.95, -5.5),
                (2.85, -7.2),
                (1.75, -7.8),
                (0.65, -7.2),
                (0.65, -8.15),
                (0.65, -6.05),
                (0.65, -5.1),
                (1.75, -5.5),
                (6.15, -5.5),
                (5.05, -6.05),
                (5.05, -7.2),
                (6.15, -6.65),
            ]
        states = [
            (i, j, a[i][j], b[m[i]][m[j]])
            for i, j in combinations(range(13), 2)
            if a[i][j] or b[m[i]][m[j]]
        ]
        pts = shift(points, ox, -0.65)
        # For legibility, place all graph atoms explicitly as in Chapter 10 ITS.
        # The product above uses the skeletal chemical convention.
        graph(
            c,
            pts,
            states,
            record["endpoint_inventories"][0],
            {1: ("a", -0.22, 0.18), 8: ("b", -0.22, 0.18)},
            paired=True,
        )
        for i in (0, 3, 4, 6):
            c.text(pts[i][0], pts[i][1], "C", "synchem")
    c.line((7.95, -3.10), (7.95, -8.95), "draw=figHair,line width=.5pt")
    c.line((4.2, -9.2), (4.8, -9.2), "synbroken")
    c.text(5.65, -9.2, "removed", "synsmall")
    c.line((7.0, -9.2), (7.6, -9.2), "synformed")
    c.text(8.45, -9.2, "formed", "synsmall")
    c.line((9.9, -9.2), (10.5, -9.2), "synbond,draw=figMuted!75")
    c.text(11.5, -9.2, "unchanged", "synsmall")
    c.save("worked_its_classes.tex")


def draw_toy(toy):
    c = Canvas(4.65)
    c.head(0.1, -0.08, "A", "Endpoints")
    c.head(4.30, -0.08, "B", "Two orbits per ITS class")
    rp = [(0.5, -1.30), (1.05, -0.9), (1.6, -1.3), (2.15, -0.9), (2.7, -1.3)]
    pp = [(0.65, -2.90), (1.20, -2.50), (1.75, -2.90), (1.20, -3.30), (1.75, -3.70)]
    graph(c, rp, [(i, j, 1, 1) for i, j in toy["reactant_edges"]])
    graph(c, pp, [(i, j, 1, 1) for i, j in toy["product_edges"]])
    c.text(3.2, -1.25, "$R$", "synsmall")
    c.text(3.2, -3.05, "$P$", "synsmall")
    c.line((1.60, -1.65), (1.60, -2.20), "synflow")
    c.text(1.8, -4.35, r"$C^*=2$", "synsmall")
    c.line((3.8, -0.75), (3.8, -4.4), "draw=figHair,line width=.5pt")
    for k, cls in enumerate(toy["classes"]):
        cx = 5.50 + 2.85 * k
        col = ("npgBlue", "npgGreen", "npgOrange", "npgPurple")[k]
        c.add(
            rf"\fill[{col}!5,rounded corners=4pt] ({cx-1.20},-.80) rectangle ({cx+1.20},-4.32);"
        )
        for orbit in range(2):
            yy = -1.10 - orbit * 0.54
            c.add(
                rf"\draw[{col},rounded corners=5pt] ({cx-.72},{yy-.18}) rectangle ({cx+.72},{yy+.18});"
            )
            c.dot(cx - 0.28, yy, col, 0.08)
            c.dot(cx + 0.28, yy, col, 0.08)
        c.line((cx, -1.99), (cx, -2.40), "synflow")
        coords = [
            (
                cx + 0.78 * cos(pi / 2 + 2 * pi * j / 5),
                -3.24 + 0.61 * sin(pi / 2 + 2 * pi * j / 5),
            )
            for j in range(5)
        ]
        graph(c, coords, cls["edge_states"], paired=True, node_numbers=True)
        c.text(cx, -4.09, rf"$\Upsilon_{{{k+1}}}$", "synsmall")
    c.save("mapping_classes.tex")


def draw_hydrogen():
    c = Canvas(4.85)
    c.head(0.1, -0.08, "A", "Pendant hydrogens")
    c.head(5.55, -0.08, "B", "Heavy optimum")
    c.head(10.8, -0.08, "C", "Full optimum")
    # Input graphs, identical heavy path; H leaves change parent.
    for row, parent in enumerate((0, 1)):
        yy = -1.3 - row * 2.2
        coords = [(1, yy), (2.4, yy), (3.8, yy)]
        for i, j in ((0, 1), (1, 2)):
            c.line(coords[i], coords[j])
        for dx, dy in ((-0.55, -0.80), (0, -1.05), (0.55, -0.80)):
            x, y = coords[parent]
            c.line((x, y), (x + dx, y + dy), "synbond,draw=npgOrange")
            c.text(x + dx, y + dy, "H", "synchem,text=npgOrange!90!black")
        for i, (x, y) in enumerate(coords):
            c.text(x, y, str(i), "synatom")
        c.text(0.35, yy, "$R$" if row == 0 else "$P$", "synsmall")
    c.line((4.55, -2.4), (5.05, -2.4), "synflow")
    # Transported full-graph overlays; H labels are matched without loss.
    for k in range(2):
        xx = 6.1 + k * 5.25
        coords = [(xx, -2.65), (xx + 1.15, -2.65), (xx + 2.3, -2.65)]
        hs = [(xx - 0.25, -1.25), (xx + 0.58, -1.0), (xx + 1.4, -1.25)]
        if k == 0:
            hs = [(xx + 0.575, -1.05), (xx + 0.575, -1.85), (xx + 0.575, -3.22)]
        c.line(coords[0], coords[1])
        c.line(coords[1], coords[2], "synbond" if k == 0 else "synbroken")
        if k == 1:
            c.add(rf"\draw[synformed] ({xx},-2.65) to[bend right=40] ({xx+2.3},-2.65);")
        for h in hs:
            c.line(coords[0], h, "synbroken" if k == 0 else "synbond")
            if k == 0:
                c.line(coords[1], h, "synformed")
        for i, (x, y) in enumerate(coords):
            c.text(x, y, str(i), "synatom")
        for x, y in hs:
            c.text(x, y, "H", "synchem")
        heavy, hpen = (0, 6) if k == 0 else (2, 0)
        for j in range(heavy + hpen):
            col = "npgBlue" if j < heavy else "npgOrange"
            c.add(rf"\fill[{col}] ({xx+j*.37},-3.60) rectangle ({xx+.30+j*.37},-3.90);")
        c.text(xx + 1.15, -4.35, f"${heavy}+{hpen}={heavy+hpen}$", "synlabel")
    c.line((5.25, -0.70), (5.25, -4.75), "draw=figHair,line width=.5pt")
    c.line((10.5, -0.70), (10.5, -4.75), "draw=figHair,line width=.5pt")
    c.save("hydrogen_objective.tex")


def draw_workflow(toy):
    c = Canvas(4.05)
    c.head(0.1, -0.08, "A", "Query")
    c.head(5.05, -0.08, "B", "Enumerate")
    c.head(11.20, -0.08, "C", "Classify")
    for k in range(2):
        pts = shift(
            [(0, 0), (0.3, 0.35), (0.6, 0), (0.9, 0.35), (1.2, 0)],
            0.45 + 2.15 * k,
            -1.6,
        )
        key = "reactant_edges" if k == 0 else "product_edges"
        graph(c, pts, [(i, j, 1, 1) for i, j in toy[key]])
        c.text(1.05 + 2.15 * k, -2.35, "$R$" if k == 0 else "$P$", "synsmall")
    c.line((1.82, -1.60), (2.40, -1.60), "synflow")
    c.text(2.1, -3.30, r"$\Omega(R,P),\quad C\;\mathrm{or}\;C^*$", "synlabel")
    # Search branches and a completion gate convey the contract without a
    # second collection of dots that could be mistaken for measured counts.
    tree = [
        (6.6, -0.9),
        (5.7, -1.6),
        (7.5, -1.6),
        (5.25, -2.3),
        (6.15, -2.3),
        (7.05, -2.3),
        (7.95, -2.3),
    ]
    for i, j in ((0, 1), (0, 2), (1, 3), (1, 4), (2, 5), (2, 6)):
        c.line(
            tree[i], tree[j], "draw=figHair" if j == 6 else "synbond,draw=npgBlue!70"
        )
    for j, (x, y) in enumerate(tree):
        c.dot(x, y, "figHair" if j == 6 else "npgBlue", 0.07)
    c.text(7.95, -2.3, r"$\times$", "synlabel,text=figBroken")
    c.line((8.25, -1.6), (9.10, -1.6), "synflow")
    c.add(r"\draw[npgGreen,line width=.8pt] (9.40,-1.6) circle (.26);")
    c.add(
        r"\draw[npgGreen,line width=1pt] (9.25,-1.6) -- (9.36,-1.70) -- (9.57,-1.44);"
    )
    c.text(9.4, -2.35, "Closed", "synsmall,text=npgGreen!80!black")
    c.line((7.05, -2.50), (7.05, -3.0), "synhint")
    c.text(7.05, -3.35, "Incomplete", "synsmall")
    c.line((4.3, -1.6), (4.9, -1.6), "synflow")
    c.line((9.9, -1.6), (10.70, -1.6), "synflow")
    for k, cls in enumerate(toy["classes"]):
        cx = 11.85 + 2.50 * (k % 2)
        cy = -1.28 - 1.62 * (k // 2)
        coords = [
            (
                cx + 0.58 * cos(pi / 2 + 2 * pi * j / 5),
                cy + 0.44 * sin(pi / 2 + 2 * pi * j / 5),
            )
            for j in range(5)
        ]
        graph(c, coords, cls["edge_states"], paired=True)
    c.text(13.1, -3.75, "One map per ITS", "synsmall")
    c.save("workflow.tex")
