name: Publish to conda-forge

on:
  release:
    types:
      - published
  push:
    branches:
      - refractor    # your intentionally misspelled branch

permissions:
  contents: read

jobs:
  build:
    name: Build Conda Package
    runs-on: ubuntu-latest
    outputs:
      pkg_paths: ${{ steps.build.outputs.paths }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          auto-update-conda: true
          auto-activate-base: true

      - name: Create & activate build environment
        shell: bash -l {0}
        run: |
          conda create -n build python=3.11 'conda-build>=3.21' -c conda-forge -y
          conda activate build

      - id: build
        name: Build conda package
        shell: bash -l {0}
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          conda activate build               # ← explicitly activate the build env
          conda build recipe --output-folder ./conda-bld

          # debug: list built files
          echo "DEBUG: Built files:"
          ls -l ./conda-bld/*/*.tar.bz2 || true

          # export paths for upload
          files=$(ls ./conda-bld/*/*.tar.bz2 | tr '\n' ' ')
          echo "paths=$files" >> $GITHUB_OUTPUT

  publish_release:
    name: Upload Release → main
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Upload to conda-forge / main
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          for pkg in ${{ needs.build.outputs.pkg_paths }}; do
            anaconda -t "$ANACONDA_TOKEN" upload \
              --user conda-forge \
              --label main \
              --no-progress \
              "$pkg"
          done

  publish_beta:
    name: Upload Refractor → beta
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/refractor'
    runs-on: ubuntu-latest
    steps:
      - name: Upload to conda-forge / beta
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          for pkg in ${{ needs.build.outputs.pkg_paths }}; do
            anaconda -t "$ANACONDA_TOKEN" upload \
              --user conda-forge \
              --label beta \
              --no-progress \
              "$pkg"
          done
