name: Test & Lint

on:
  push:
    branches: [ "main", "dev", "maintain", "refractor" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 0) Checkout repository
      - uses: actions/checkout@v3

      # 1) Install Miniconda (downloaded, not the removed “bundled” one)
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          miniconda-version: "latest"      # <<<–– FIXES the “No installed conda …” error
          environment-file: environment.yml
          activate-environment: synkit-env
          use-mamba: true                  # fast solver, optional but nice

      # 2) Install mod only on Linux (skip elsewhere)
      - name: Install mod (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: conda run -n synkit-env conda install -c jakobandersen -c conda-forge "mod>=0.17" -y

      # 3) Optional extra project deps via pip
      - name: Install project requirements (pip)
        if: hashFiles('requirements.txt') != ''
        run: conda run -n synkit-env pip install -r requirements.txt

      # 4) Lint
      - name: Lint
        run: |
          conda run -n synkit-env flake8 . \
            --count --select=E9,F63,F7,F82 --show-source --statistics
          ./lint.sh

      # 5) Test
      - name: Test
        run: conda run -n synkit-env ./pytest.sh
